-- 코드를 입력하세요
SELECT 
    MP.MEMBER_NAME, 
    RR.REVIEW_TEXT, 
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_NAME = (
    SELECT MP.MEMBER_NAME
    FROM MEMBER_PROFILE MP
    JOIN REST_REVIEW RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY MP.MEMBER_NAME
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT;